### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by hakluke** [eikendev/sectxt#1]
Hey eikendev!

Awesome work on this tool! My original goal with haksecuritytxt was to output the results in a format that works for discloseio [which you can view here](https://github.com/disclose/disclose/blob/master/program-list/program-list.json) but honestly I probably won't get around to actually implementing that for a while.

I would love to see this tool work with that output!

Also thanks for the shoutout in the README :)

hakluke

**Comment by eikendev** [comment]
Hi, thank you for opening this issue!

So I've looked up the format and it seems that the field `policy_url` is required by discloseio. However, a security.txt file does not need to have a `Policy` field. So what should be done in that case? Should no JSON object for that domain be generated or should we place a dummy value for the missing policy URL?

Just to confirm, what we need is something like this as a minimal example:
```json
  {
    "program_name": "tesla.com",
    "policy_url": "https://bugcrowd.com/tesla",
    "submission_url": "https://bugcrowd.com/tesla/report"
  }
```

The `program_name` would be derived from the domain that was specified by the user.

**Comment by hakluke** [comment]
Yeah that looks good. I think maybe the policy URL could just be the url of
the security.txt file? Unsure.

**Comment by eikendev** [comment]
In case you are wondering, I'm currently working out a parser for the file format. With this parser, this should be relatively easy to implement.

**Comment by eikendev** [comment]
Something similar can now be achieved in version 0.2.1:
```bash
echo github.com | ./target/debug/sectxt | jq
```
will yield
```json
{
  "level": "INFO",
  "fields": {
    "domain": "github.com",
    "content": {
      "acknowledgments": [
        "https://hackerone.com/github/hacktivity"
      ],
      "canonical": [
        "https://github.com/.well-known/security.txt"
      ],
      "contact": [
        "https://hackerone.com/github"
      ],
      "encryption": [],
      "expires": "2023-04-11T22:47:25+00:00",
      "extension": [],
      "hiring": [
        "https://github.com/about/careers"
      ],
      "policy": [
        "https://bounty.github.com"
      ],
      "preferred_languages": "en"
    },
    "status": "OK"
  }
}
```
Takes a bit of `jq` finetuning to select the right fields.
